<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Hosting\Shared.Hosting.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>

</Project>
